branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@terrestris/maven-semantic-release"
    - mavenTarget: deploy
      clean: true
      updateSnapshotVersion: true
      processAllModules: true
  - - "@semantic-release/github"
    - assets:
      - path: "mde-importer/target/mde-importer-*.jar"
      - path: "mde-services/target/mde-services-*.jar"
  - "@semantic-release/git"
